- concat
- merge
- join
- handling key and index

## concat
- it is used combine  dataframe vertically or horizontally

In [40]:
import pandas as pd
dic = { "mark":[88,76,92,44,59]
       }
dic1= {"age":[20,21,22,24,19]}
df1 = pd.DataFrame(dic)
df2 = pd.DataFrame(dic1)
rsult2 = pd.concat([df1,df2],keys=['x','y','z'])
print("adding two or more dictonary and key are separated by dictonary")
print(rsult2)
rsult1 = pd.concat([df1,df2],ignore_index=True)
print("index ignore karega ")
print(rsult1)
rsult3 = pd.concat([df1,df2],ignore_index=True ,axis =1)
print("column mai add hoga")
print(rsult3)
rsult4 = pd.concat([df1,df2],ignore_index=True ,axis =0)
print("row mai add hoga")
print(rsult4)

adding two or more dictonary and key are separated by dictonary
     mark   age
x 0  88.0   NaN
  1  76.0   NaN
  2  92.0   NaN
  3  44.0   NaN
  4  59.0   NaN
y 0   NaN  20.0
  1   NaN  21.0
  2   NaN  22.0
  3   NaN  24.0
  4   NaN  19.0
index ignore karega
   mark   age
0  88.0   NaN
1  76.0   NaN
2  92.0   NaN
3  44.0   NaN
4  59.0   NaN
5   NaN  20.0
6   NaN  21.0
7   NaN  22.0
8   NaN  24.0
9   NaN  19.0
column mai add hoga
    0   1
0  88  20
1  76  21
2  92  22
3  44  24
4  59  19
row mai add hoga
   mark   age
0  88.0   NaN
1  76.0   NaN
2  92.0   NaN
3  44.0   NaN
4  59.0   NaN
5   NaN  20.0
6   NaN  21.0
7   NaN  22.0
8   NaN  24.0
9   NaN  19.0

C:\Users\shive\AppData\Local\Temp\ipykernel_24236\4171333940.py:7: FutureWarning: The behavior of pd.concat with len(keys) != len(objs) is deprecated. In a future version this will raise instead of truncating to the smaller of the two sequences
  rsult2 = pd.concat([df1,df2],keys=['x','y','z'])

## merge()
- Purpose: Combines rows from two DataFrames where values in key columns match.
- it work like the join in sql 

### Parameters:

- left, right: The two DataFrames you want to merge.

- on: Column(s) to join on (must exist in both DataFrames).

- how: Type of join:

- 'inner' → only matching rows (default).

- 'left' → all rows from left DataFrame + matches from right.

- 'right' → all rows from right DataFrame + matches from left.

- 'outer' → all rows from both, filling missing with NaN.

In [50]:
dic = { "id":[3,4,9,6],
       "name":['A',"B","C","D"]
       }
dic1= {"id":[2,3,4,5],
       "name":['A',"B","C","D"]
       }
df1 = pd.DataFrame(dic)
df2 = pd.DataFrame(dic1)
print(pd.merge(df1,df2,on="id"))
print("--------------")
pd.merge(df1,df2,on="name")
# pd.merge(df1,df2,on="mark")

   id name_x name_y
0   3      A      B
1   4      B      C
--------------

   id_x name  id_y
0     3    A     2
1     4    B     3
2     9    C     4
3     6    D     5

## inner merge()
-

In [ ]:
pd.merge(df1,df2,on="id",how="inner")

   id name_x name_y
0   3      A      B
1   4      B      C

In [55]:
pd.merge(df1,df2,on="name",how="outer")

   id_x name  id_y
0     3    A     2
1     4    B     3
2     9    C     4
3     6    D     5

In [57]:
pd.merge(df1,df2,on="id",how="right")

   id name_x name_y
0   2    NaN      A
1   3      A      B
2   4      B      C
3   5    NaN      D

In [60]:
pd.merge(df1,df2,on="id",how="left")

   id name_x name_y
0   3      A      B
1   4      B      C
2   9      C    NaN
3   6      D    NaN